shud necrolog, cg_conObituaries, scores blocker
snems/OSP2 pull request #20
Opened 2024-12-05 16:41 UTC by scoqx

Added necrolog (obituary) for superhud. 
Example config hud/default.cfg
cg_conObituaries 0/1 - draw obituary messages in console
Scores blocker is back, but inverted

2024-12-05 17:06 UTC, snems requested changes

2024-12-05 17:06 UTC, snems commented on code/cgame/cg_superhud_element_necrolog.c
> +	if (team != 1 && team != 2)
if (team != TEAM_RED && team != TEAM_BLUE)

2024-12-05 17:12 UTC, scoqx commented on code/cgame/cg_superhud_private.h
> +#define SE_SCORES     0x00000120 // hide when scores up
Если ставлю 20, ничего не работает

2024-12-05 17:12 UTC, scoqx commented on code/cgame/cg_superhud_element_necrolog.c
> +	if (team != 1 && team != 2)
Неа, там значение инт. От 0

2024-12-05 17:13 UTC, scoqx commented on code/cgame/cg_superhud_private.h
> +#define SHUD_MAX_NECROLOG_LINES 16
Вот тут забыл, поправлю

2024-12-05 17:13 UTC, scoqx commented on code/cgame/cg_superhud_element_necrolog.c
> +	}
Остатки))

2024-12-06 10:59 UTC, scoqx commented on code/cgame/cg_superhud_element_necrolog.c
> +	if (team != 1 && team != 2)
А, там индекс... ну проще же цифру передавать, чем имя)

2024-12-06 10:59 UTC, scoqx commented on code/cgame/cg_superhud_element_necrolog.c
> +	if (team != 1 && team != 2)
typedef enum
{
	TEAM_FREE,
	TEAM_RED,
	TEAM_BLUE,
	TEAM_SPECTATOR,
	TEAM_4,
	TEAM_5,
	TEAM_6,
	TEAM_7,
	TEAM_NUM_TEAMS
} team_t;

2024-12-06 15:07 UTC, merged