cg_drawCenterMessages 0/1
snems/OSP2 pull request #24
Opened 2024-12-29 12:27 UTC by scoqx

Вывод сообщений в центре экрана. Приветственное сообщение, когда кто-то заходит на сервер. Фраг и сообщения о разморозке. Альтернатива cg_centerTime 0-1000. Но эта команда контролируется сервером.  Сейчас отключили возможность её регулировать) 
Работает только на осп элементы.

2024-12-30 16:15 UTC, snems requested changes

2024-12-30 16:15 UTC, snems commented on code/cgame/cg_local.h
> +void CG_LocalEventCvarChanged_cg_drawCenterMessages(cvarTable_t* cvart);
Тут ты объявил событие при изменении переменной

2024-12-30 16:15 UTC, snems commented on code/cgame/cg_localevents.c
> +void CG_LocalEventCvarChanged_cg_drawCenterMessages(cvarTable_t* cvart)
Вот оно само, ограничивает значение

2024-12-30 16:15 UTC, snems commented on code/cgame/cg_main.c
> +	{ &cg_drawCenterMessages, "cg_drawCenterMessages", "1", CVAR_ARCHIVE },
А вот оно не добавлено в контекст переменной, т.е. не используется.
Предлагаю вообще его убрать, ничего страшного, если там не будет не только 0 или 1.

2025-01-20 11:43 UTC, scoqx commented
Исправил. Если честно я думал наличие LocalEventCvarChanged обязательным

2025-01-20 13:35 UTC, merged